### PR TITLE
Custom CardView background color

### PR DESCRIPTION
**Pull request by k0shk0sh**
- Added the ability to add custom `CardView backgroundColor` its useful when Apps such as `FastHub` has custom themes that needs to change the `CardView backgroundColor`.
- Added an example showing how the `color` could be changed.
- Wrapped the `Activity` in the `AsyncTask` into `WeakReference` to avoid leakage.

I hope you can make a new release before tomorrow :p

### CODE REVIEW

**Comment by daniel-stoneuk** [comment]
Sure can, I presume you've tested the demo app and all?

**Comment by k0shk0sh** [comment]
Yep I did & triple confirmed :)

**Comment by daniel-stoneuk** [comment]
Awesome! Looks like a great addition - thanks very much.

**Comment by k0shk0sh** [comment]
Thank you for the wonderful library :)

**Comment by daniel-stoneuk** [comment]
https://github.com/daniel-stoneuk/material-about-library/releases/tag/2.1.0

Thanks!

**Comment by k0shk0sh** [comment]
@daniel-stoneuk here it is in action :p









_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
